### PR TITLE
Shadow Fiend Facets Implementation

### PR DESCRIPTION
**Pull request by Dnarok**
Attempt at implementing the SF facets.

Some things are incomplete, but this carries about 90% of the features. Some important things that happened:

- Shadowraze reimplemented as a Lua ability, was previously just a data-driven modification of the vanilla Shadowraze.
- Most of the spells renamed as "_ebf" versions, to avoid the game adding the default tooltip values to the ability.

Some things that still need to be done:

- [ ] Precaching particles? 
    - At least in the tools, I'm getting some missing particles (but not all?)
- [x] Necromastery max stacks on kills.
    - Has been difficult to implement entirely within the single modifier, due to the resets between rounds clearing out the modifier's internal values. Might just have to have two hidden stack-based modifiers to keep track.
- [x] Some more thorough testing of Psyche and Id, since they're a bit more complicated than Ego.
- [x] Tooltips for some of the modifiers added here.
- [ ] Ego Shadowraze/Requiem should probably show as Physical damage, not Magical damage, on the ability tooltip.
    - No idea how to do that in a way that's decided by the facet. Might require Panorama additions?
- [ ] Removing Shadowfiend's two vanilla facets.
    - I don't know why they still show up, maybe it's just a tools thing.
- [x] Integrating/fixing talents, and figuring out how they'll interact with the facets.

### CODE REVIEW

**Comment by Dnarok** [comment]
I've patched up most of the bugs I've found, and have managed a solo nightmare playthrough on each facet.

Balance-wise, he's way overtuned with the numbers he had previously, but those are easy enough to tweak.

**Comment by Yahnich** [comment]
can you undo removing the code that enabled the previous talents? there's no harm in keeping them and i'll decide whether or not they can stay in the finished product once i have my hands on this properly

**Comment by Dnarok** [comment]
> can you undo removing the code that enabled the previous talents? there's no harm in keeping them and i'll decide whether or not they can stay in the finished product once i have my hands on this properly

I think the only one that existed previously that doesn't now is the Presence affecting allies, and that's just because I forgot to implement it again. I'll do that in a pass a bit later.

**Comment by Yahnich** [comment]
necromastery immortality talent support is also gone as far as i cant tell? regardless good job!

**Comment by Dnarok** [comment]
> necromastery immortality talent support is also gone as far as i cant tell? regardless good job!

Ah, I see, no I just renamed the talents back to "special_bonus_unique_nevermore_#", since they were half-and-half, and also out of order. Immortality is now #8, top left talent for all. I also made is "reincarnate if necromastery stacks are greater than the base max", since you can increase max stacks now.

**Comment by Yahnich** [comment]
are you going to be doing more work on this, or do i just merge and figure it out myself?

**Comment by Dnarok** [comment]
Yeah, sorry, I've not got the time right now to work on it (and the last few checkboxes I'm not entirely sure how to do, either.)

Hopefully it's at a good jumping off point!

**Pull request merged**
